name: bench

on:
  workflow_dispatch:
    inputs:
      library:
        type: choice
        description: which library/libraries to run
        options:
          - All
          - 00_mtkruto
          - 01_fasttelethon
          - 02_mtcute
          - 03_telethon
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 00_mtkruto
  mtkruto:
    if: github.event.inputs.library == '00_mtkruto' || github.event.inputs.library == 'All'
    runs-on: ubuntu-latest
    env:
      AUTH_STRING: ${{ secrets.AUTH_STRING_00 }}
      MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2

      - run: |
          cd 00_mtkruto/
          deno install
          deno -A main.ts

          cd ../
          ./_commit.sh

  # 01_fasttelethon
  fasttelethon:
    if: github.event.inputs.library == '01_fasttelethon' || github.event.inputs.library == 'All'
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      AUTH_STRING: ${{ secrets.AUTH_STRING_01 }}
      MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: python -m pip install poetry

      - run: |
          cd 01_fasttelethon/
          poetry install
          poetry run python main.py

          cd ../
          ./_commit.sh

  # 02_mtcute
  mtcute:
    if: github.event.inputs.library == '02_mtcute' || github.event.inputs.library == 'All'
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      AUTH_STRING: ${{ secrets.AUTH_STRING_02 }}
      MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"

      - run: |
          cd 02_mtcute/
          pnpm install
          node main.ts

          cd ../
          ./_commit.sh

  # 03_telethon
  telethon:
    if: github.event.inputs.library == '03_telethon' || github.event.inputs.library == 'All'
    runs-on: ubuntu-latest
    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      AUTH_STRING: ${{ secrets.AUTH_STRING_03 }}
      MESSAGE_LINK: ${{ secrets.MESSAGE_LINK }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: python -m pip install poetry

      - run: |
          cd 03_telethon/
          poetry install
          poetry run python main.py

          cd ../
          ./_commit.sh
